# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58d8c3710cacbbcbb094fe1cfc95ebd45c356a1637ef615eb0dd14cef639969e419f16bf5bd679641be558de3e5e92609cb2c30085631793c89225d910874f2b

test:
  secret_key_base: f946c7b17de3c5d231cdaec9c6a73054f178cb306d3500439d3f4fbfff6dd63a151b8cb6398d3fc0225f17ee2bf3c74bdbdf91e71c9219d862b8ce7431482f8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
